### ISSUE TITLE
Как работает данный плагин?

### ISSUE THREAD

**Issue by odeann** [ermashov/cordova-plugin-cryptopro#1]
Алексей, приветствую!
Не нашёл другого способа связаться с вами.
Я ищу плагин для кордовы, который позволит нам подписывать (XMLDsig) сообщения на Андройде через КриптоПро.

Этот плагин такое умеет? Есть где-нибудь описание?

**Comment by yuri-dev** [comment]
Похоже, для cordova все еще нет.

**Comment by ermashov** [comment]
Добрый день, давно не заходил на гитхаб.
Пример использования:
//Получаем список сертификатов
window.plugins.cryptopro.getCertificates(function(cert){
            alert(cert);
        },function(error){
            alert(error);
        })
//Подписываем
window.plugins.cryptopro.singCades({
            keyStoreType:"Aktiv Rutoken ECP BT 1",
            alias:"29824913@2019-03-29-CompanyName",
            pin:"1234567890",
            data:"ваываыва",
            detached:"N",
        },
        function(sing){
            alert(sing);
        },function(error){
            alert(error);
        })

Если честно детали не помню.

Функционала плагина для формирования XMLDsig вам не хватит. Плагин позволяет получать список сертификатов в контейнерах и подписывать данные.
